// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5AMEh4FWlXR62oi6P71x1ByJBJBo7TgE',
    appId: '1:497453396031:web:c636a0127d5f35a264488a',
    messagingSenderId: '497453396031',
    projectId: 'application-b6a45',
    authDomain: 'application-b6a45.firebaseapp.com',
    storageBucket: 'application-b6a45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmouDKhqmcH2oSJzeXRbxv2e1PJ5qick',
    appId: '1:497453396031:android:a6503436d20dc6fb64488a',
    messagingSenderId: '497453396031',
    projectId: 'application-b6a45',
    storageBucket: 'application-b6a45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSSNdcmwSlGXNAt9q2pcvXU1Ks63rSFk',
    appId: '1:497453396031:ios:7a7f94387c8c393c64488a',
    messagingSenderId: '497453396031',
    projectId: 'application-b6a45',
    storageBucket: 'application-b6a45.appspot.com',
    iosClientId: '497453396031-5suse1b80db2ecjmrsgu5e9bh5t1ug0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSSNdcmwSlGXNAt9q2pcvXU1Ks63rSFk',
    appId: '1:497453396031:ios:2f25c0aa0d59cbe164488a',
    messagingSenderId: '497453396031',
    projectId: 'application-b6a45',
    storageBucket: 'application-b6a45.appspot.com',
    iosClientId: '497453396031-mapaj8mthb82sgmnid0lpqn6por60u81.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp.RunnerTests',
  );
}
